import type MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '0.0.0',
  date: '2023-02-10T12:35:57.021Z',
};
export default meta;
